### ISSUE TITLE
How do you set game rewards?

### ISSUE THREAD

**Issue by qiaoxianfeng** [buenohernandez/dqn_car_conv2D_SGD#1]
Thank you for your code, can you tell me how you set the game rewards if it is convenient for you?

**Comment by buenohernandez** [comment]
Hello and thank you for your message @qiaoxianfeng.

On the example [using values instead](https://github.com/buenohernandez/Self-driving-car-using-Reinforcement-Learning-Neural-Networks) of images if you run the game_cart.py file, you can see the car antennae for collision detection and a debugging showing the state, and reward.

For the example [using images](https://github.com/buenohernandez/Self-driving-car-using-Reinforcement-Learning-for-Computer-Vision), on the line 229 of the game_cart.py file if you change from:
`self.sensors_calc(pos, False)` to `self.sensors_calc(pos, True)` you can see that I used many more antennae and there is also the debugging values.

For choosing the values, if it had a good behavior I gave it +x, if it had a bad behavior I gave it a -y, for the amplitude of the values of the rewards given I kind of went on instinct:

(+10) for crossing the finishing line
( -10) for running on the grass and restarting
( - X ), with X being how much the car/cart is heading to out of track, with max value being 1.

    def bound_check(self):
        x = int(self.x) + 24//div
        y = int(self.y) + 24//div
        self.pix  = course.get_at((x,y))
        self.sp = sum([abs(TRACK[z] - self.pix[z]) for z in range(len(TRACK))])

        if self.check_finish_line(x, y):    return 10, True <----- Here

        if self.sp > 50:
            self.restart = True
            return -10, False  <----- Here

        if np.count_nonzero(np.array(self.sens_lens)) == 0: return 0, False
        else:   return -round(np.count_nonzero(np.array(self.sens_lens)) / float(len(self.sensors)), 2), False  <----- Here

Did it help? 😃

**Comment by qiaoxianfeng** [comment]
Thank you very much for your help, it is very helpful to me.
