### ISSUE TITLE
How do I cite this model?

### ISSUE THREAD

**Issue by qiaoxianfeng** [buenohernandez/dqn_car_conv2D_SGD#2]
Hello, I want to use this unmanned driving model as a verification test in my paper. How do I cite this model? Are there related papers?

**Comment by buenohernandez** [comment]
Hello, the algorithm used is similar to what is usually used on _openai gym dqn cartpole_ examples, I believe that's a good starting point to look for which paper to citate.

**Comment by qiaoxianfeng** [comment]
Thank you for your answer.
